import 'package:flutter/material.dart';

void main() {
  runApp(const Profil());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Profil extends StatelessWidget {
  const Profil({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          const Profile(),
        ]),
      ),
    );
  }
}

class Profile extends StatelessWidget {
  const Profile({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: const BoxDecoration(color: Color(0xFFF1F1F1)),
          child: Stack(
            children: [
              Positioned(
                left: -3,
                top: -4,
                child: Container(
                  width: 438,
                  height: 243,
                  decoration: const ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(-0.00, -1.00),
                      end: Alignment(0, 1),
                      colors: [Color(0xFF54E6B5), Color(0x0031D69F)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(22),
                        topRight: Radius.circular(23),
                      ),
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 127,
                top: 166,
                child: Text(
                  'Ahmed Ben Ali ',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 24,
                    fontFamily: 'DM Sans',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 155,
                top: 53,
                child: Container(
                  width: 104,
                  height: 104,
                  decoration: const ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/104x104"),
                      fit: BoxFit.fill,
                    ),
                    shape: OvalBorder(
                      side: BorderSide(width: 2, color: Colors.white),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 430,
                  height: 46,
                  padding: const EdgeInsets.only(left: 29, right: 27),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      const Text(
                        '9:41',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 16,
                          fontFamily: 'SF Pro Text',
                          fontWeight: FontWeight.w600,
                          height: 0,
                        ),
                      ),
                      const SizedBox(width: 95),
                      Row(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.end,
                        children: [
                          const SizedBox(width: 8),
                          const SizedBox(width: 8),
                          Container(
                            width: 28,
                            height: 13,
                            clipBehavior: Clip.antiAlias,
                            decoration: const BoxDecoration(),
                            child: const Stack(children: [
                            
                            ]),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 240,
                top: 117,
                child: Container(
                  width: 32,
                  height: 32,
                  decoration: const ShapeDecoration(
                    color: Colors.white,
                    shape: OvalBorder(
                      side: BorderSide(width: 1, color: Colors.white),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 260,
                child: Container(
                  width: 360,
                  height: 586,
                  decoration: ShapeDecoration(
                    color: const Color(0x11939393),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(31),
                    ),
                    shadows: const [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 351,
                child: Container(
                  width: 361,
                  decoration: const ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFBDBDBD),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 423,
                child: Container(
                  width: 361,
                  decoration: const ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFBDBDBD),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 495,
                child: Container(
                  width: 361,
                  decoration: const ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFBDBDBD),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 567,
                child: Container(
                  width: 361,
                  decoration: const ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFBDBDBD),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 639,
                child: Container(
                  width: 361,
                  decoration: const ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFBDBDBD),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 706,
                child: Container(
                  width: 361,
                  decoration: const ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFBDBDBD),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 775,
                child: Container(
                  width: 361,
                  decoration: const ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFBDBDBD),
                      ),
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 114,
                top: 307,
                child: Text(
                  'Modifier le profile ',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'DM Sans',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              const Positioned(
                left: 114,
                top: 379,
                child: Text(
                  'Sécurité',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'DM Sans',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              const Positioned(
                left: 114,
                top: 451,
                child: Text(
                  'Paramètres',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'DM Sans',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              const Positioned(
                left: 115,
                top: 595,
                child: Text(
                  'Historique des transactions',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'DM Sans',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              const Positioned(
                left: 114,
                top: 666,
                child: Text(
                  'FAQ',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'DM Sans',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              const Positioned(
                left: 115,
                top: 732,
                child: Text(
                  'À propos de l/n application',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'DM Sans',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              const Positioned(
                left: 114,
                top: 801,
                child: Text(
                  'Se déconnecter',
                  style: TextStyle(
                    color: Color(0xFFBF2135),
                    fontSize: 16,
                    fontFamily: 'DM Sans',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 68,
                top: 446,
                child: Container(
                  width: 24,
                  height: 24,
                  padding: const EdgeInsets.only(top: 2, right: 3.15, bottom: 0.05),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 20.85,
                        height: 21.95,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 13.72,
                              top: 7.68,
                              child: Transform(
                                transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                child: Container(
                                  width: 6.59,
                                  height: 6.59,
                                  decoration: const ShapeDecoration(
                                    shape: OvalBorder(
                                      side: BorderSide(
                                        width: 1.50,
                                        strokeAlign: BorderSide.strokeAlignCenter,
                                        color: Color(0xFF2B3F6C),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 20.85,
                                height: 21.95,
                                decoration: ShapeDecoration(
                                  image: const DecorationImage(
                                    image: NetworkImage("https://via.placeholder.com/21x22"),
                                    fit: BoxFit.fill,
                                  ),
                                  shape: RoundedRectangleBorder(
                                    side: const BorderSide(
                                      width: 1.50,
                                      strokeAlign: BorderSide.strokeAlignCenter,
                                      color: Color(0xFF2B3F6C),
                                    ),
                                    borderRadius: BorderRadius.circular(0.80),
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 56,
                top: 386,
                child: Container(width: 24, height: 24),
              ),
              Positioned(
                left: 67,
                top: 305,
                child: Container(
                  width: 17,
                  height: 21.25,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 13.36,
                        top: 0,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                          child: Container(
                            width: 9.71,
                            height: 9.71,
                            decoration: const ShapeDecoration(
                              shape: OvalBorder(
                                side: BorderSide(
                                  width: 1.50,
                                  strokeAlign: BorderSide.strokeAlignCenter,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 65,
                top: 374,
                child: Container(
                  width: 24,
                  height: 24,
                  padding: const EdgeInsets.symmetric(horizontal: 4, vertical: 3),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 16,
                        height: 18,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 6,
                              child: Container(
                                width: 16,
                                height: 12,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: const BorderSide(
                                      width: 1.50,
                                      strokeAlign: BorderSide.strokeAlignCenter,
                                    ),
                                    borderRadius: BorderRadius.circular(4),
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 65,
                top: 590,
                child: Container(
                  width: 24,
                  height: 24,
                  padding: const EdgeInsets.all(2),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 20,
                        height: 20,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 4,
                              child: Container(
                                width: 20,
                                height: 16,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: const BorderSide(
                                      width: 1.50,
                                      strokeAlign: BorderSide.strokeAlignCenter,
                                      color: Color(0xFF2B3F6C),
                                    ),
                                    borderRadius: BorderRadius.circular(5),
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 65,
                top: 661,
                child: Container(
                  width: 24,
                  height: 24,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 2,
                        top: 2,
                        child: Container(
                          width: 20,
                          height: 20,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: const BorderSide(
                                width: 1.50,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Color(0xFF2B3F6C),
                              ),
                              borderRadius: BorderRadius.circular(5),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 5.80,
                        top: 10.80,
                        child: Container(
                          width: 12.50,
                          height: 2.50,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 2.50,
                                  height: 2.50,
                                  decoration: const ShapeDecoration(
                                    color: Color(0xFF2B3F6C),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 5,
                                top: 0,
                                child: Container(
                                  width: 2.50,
                                  height: 2.50,
                                  decoration: const ShapeDecoration(
                                    color: Color(0xFF2B3F6C),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 10,
                                top: 0,
                                child: Container(
                                  width: 2.50,
                                  height: 2.50,
                                  decoration: const ShapeDecoration(
                                    color: Color(0xFF2B3F6C),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 71,
                top: 733,
                child: Container(
                  width: 24,
                  height: 24,
                  padding: const EdgeInsets.only(right: 4, bottom: 4),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 20,
                        height: 20,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 20,
                                height: 20,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: const BorderSide(
                                      width: 1.50,
                                      strokeAlign: BorderSide.strokeAlignCenter,
                                      color: Color(0xFF2B3F6C),
                                    ),
                                    borderRadius: BorderRadius.circular(5),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 8.50,
                              top: 5,
                              child: SizedBox(
                                width: 2,
                                height: 10,
                                child: Stack(children: [
                                
                                ]),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const Positioned(
                left: 113,
                top: 521,
                child: Text(
                  'Mes voitures ',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'DM Sans',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 68,
                top: 799,
                child: Container(
                  width: 24,
                  height: 24,
                  padding: const EdgeInsets.only(top: 2, left: 3, right: 2, bottom: 2),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 19,
                        height: 20,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 19,
                              top: 7,
                              child: Transform(
                                transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                child: Container(
                                  width: 13,
                                  height: 6,
                                  child: Stack(children: [
                                  
                                  ]),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 249,
                top: 125,
                child: Container(
                  width: 14,
                  height: 14,
                  clipBehavior: Clip.antiAlias,
                  decoration: const BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 14,
                        height: 14,
                        child: Stack(children: [
                        
                        ]),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 864,
                child: Container(
                  width: 436,
                  height: 67,
                  decoration: const ShapeDecoration(
                    color: Color(0xFF54E6B5),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(24),
                        topRight: Radius.circular(24),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 57,
                top: 885,
                child: Container(
                  width: 26,
                  height: 26,
                  clipBehavior: Clip.antiAlias,
                  decoration: const BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                    
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 365,
                top: 885,
                child: Container(
                  width: 22,
                  height: 26.39,
                  child: Stack(children: [
                  
                  ]),
                ),
              ),
              Positioned(
                left: 203,
                top: 883,
                child: Container(
                  width: 30,
                  height: 29.98,
                  child: Stack(children: [
                  
                  ]),
                ),
              ),
              Positioned(
                left: 287,
                top: 886,
                child: Container(
                  width: 24,
                  height: 27,
                  clipBehavior: Clip.antiAlias,
                  decoration: const BoxDecoration(),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                    
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 158,
                top: 203,
                child: Text(
                  '+216 12345678',
                  style: TextStyle(
                    color: Colors.black.withOpacity(0.5899999737739563),
                    fontSize: 16,
                    fontFamily: 'DM Sans',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}